version: '3.4'

services:
  ajv:
    image: ajv
    build:
      context: reactapp/node_modules/ajv
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
